export interface TopicConfig {
  slug: string;
  label: string;
  description: string;
  bannerColor: string;
  iconClass: string;
  skill: string;
}

export interface SectionConfig {
  slug: string;
  label: string;
  description: string;
  bannerColor: string;
  iconClass: string;
  topics: TopicConfig[];
}

export const STUDY_SECTIONS: SectionConfig[] = [
  {
    slug: 'backend',
    label: 'Backend',
    description: 'APIs REST, microsserviços, Node.js, Java, Python e arquiteturas server-side.',
    bannerColor: 'linear-gradient(135deg, #4f46e5, #7c3aed)',
    iconClass: 'server',
    topics: [
      {
        slug: 'nodejs',
        label: 'Node.js',
        description: 'Fundamentos, APIs assíncronas, Express, Fastify e ecossistema Node.',
        bannerColor: 'linear-gradient(135deg, #166534, #16a34a)',
        iconClass: 'server',
        skill: 'Runtime',
      },
      {
        slug: 'java',
        label: 'Java',
        description: 'Spring Boot, JPA, injeção de dependência e ecossistema Java.',
        bannerColor: 'linear-gradient(135deg, #b45309, #d97706)',
        iconClass: 'code',
        skill: 'Linguagem',
      },
      {
        slug: 'python',
        label: 'Python',
        description: 'FastAPI, Django, automações e integração com ferramentas de IA.',
        bannerColor: 'linear-gradient(135deg, #1d4ed8, #3b82f6)',
        iconClass: 'code',
        skill: 'Linguagem',
      },
      {
        slug: 'rest-api',
        label: 'APIs REST',
        description: 'Design de APIs, versionamento, autenticação, documentação e boas práticas.',
        bannerColor: 'linear-gradient(135deg, #374151, #6b7280)',
        iconClass: 'link',
        skill: 'Backend',
      },
      {
        slug: 'microsservicos',
        label: 'Microsserviços',
        description: 'Decomposição de serviços, comunicação, resiliência e padrões de arquitetura.',
        bannerColor: 'linear-gradient(135deg, #4f46e5, #7c3aed)',
        iconClass: 'share-2',
        skill: 'Arquitetura',
      },
      {
        slug: 'arquitetura-backend',
        label: 'Arquitetura Backend',
        description: 'Clean Architecture, DDD, CQRS e padrões de design orientados a domínio.',
        bannerColor: 'linear-gradient(135deg, #1e40af, #3b82f6)',
        iconClass: 'building-2',
        skill: 'Arquitetura',
      },
    ],
  },
  {
    slug: 'banco-de-dados',
    label: 'Banco de Dados',
    description: 'SQL, NoSQL, modelagem de dados, otimização e estratégias de persistência.',
    bannerColor: 'linear-gradient(135deg, #0891b2, #0e7490)',
    iconClass: 'database',
    topics: [
      {
        slug: 'mysql',
        label: 'MySQL',
        description: 'DDL, DML, índices, procedures, triggers e administração.',
        bannerColor: 'linear-gradient(135deg, #1d4ed8, #3b82f6)',
        iconClass: 'database',
        skill: 'SQL',
      },
      {
        slug: 'postgresql',
        label: 'PostgreSQL',
        description: 'Recursos avançados do Postgres, JSONB, extensões e tuning.',
        bannerColor: 'linear-gradient(135deg, #1e3a5f, #2563eb)',
        iconClass: 'database',
        skill: 'SQL',
      },
      {
        slug: 'mongodb',
        label: 'MongoDB',
        description: 'Documentos, coleções, aggregation pipeline e modelagem NoSQL.',
        bannerColor: 'linear-gradient(135deg, #166534, #16a34a)',
        iconClass: 'database',
        skill: 'NoSQL',
      },
      {
        slug: 'redis',
        label: 'Redis',
        description: 'Cache, pub/sub, estruturas de dados e estratégias de expiração.',
        bannerColor: 'linear-gradient(135deg, #dc2626, #ef4444)',
        iconClass: 'database',
        skill: 'Cache',
      },
      {
        slug: 'modelagem',
        label: 'Modelagem de Dados',
        description: 'Entidade-Relacionamento, normalização, desnormalização e modelagem dimensional.',
        bannerColor: 'linear-gradient(135deg, #0891b2, #0e7490)',
        iconClass: 'network',
        skill: 'Database',
      },
    ],
  },
  {
    slug: 'cloud',
    label: 'Cloud Computing',
    description: 'AWS, Azure, GCP, certificações e serviços gerenciados na nuvem.',
    bannerColor: 'linear-gradient(135deg, #0369a1, #0ea5e9)',
    iconClass: 'cloud',
    topics: [
      {
        slug: 'aws',
        label: 'AWS',
        description: 'EC2, S3, Lambda, RDS, ECS, IAM, CloudFormation e principais serviços.',
        bannerColor: 'linear-gradient(135deg, #c25b0a, #f59e0b)',
        iconClass: 'cloud',
        skill: 'Cloud',
      },
      {
        slug: 'azure',
        label: 'Azure',
        description: 'VMs, Azure Functions, AKS, CosmosDB e serviços Microsoft Azure.',
        bannerColor: 'linear-gradient(135deg, #0369a1, #0ea5e9)',
        iconClass: 'cloud',
        skill: 'Cloud',
      },
      {
        slug: 'gcp',
        label: 'Google Cloud',
        description: 'GKE, Cloud Run, BigQuery, Pub/Sub e serviços Google Cloud.',
        bannerColor: 'linear-gradient(135deg, #1d4ed8, #dc2626)',
        iconClass: 'cloud',
        skill: 'Cloud',
      },
      {
        slug: 'fundamentos',
        label: 'Fundamentos Cloud',
        description: 'Modelos IaaS, PaaS, SaaS, regiões, disponibilidade e segurança na nuvem.',
        bannerColor: 'linear-gradient(135deg, #0891b2, #0e7490)',
        iconClass: 'book',
        skill: 'Cloud',
      },
      {
        slug: 'serverless',
        label: 'Serverless',
        description: 'Functions as a Service, event-driven, escalabilidade automática e custo por uso.',
        bannerColor: 'linear-gradient(135deg, #4f46e5, #7c3aed)',
        iconClass: 'zap',
        skill: 'Cloud',
      },
    ],
  },
  {
    slug: 'containers-kubernetes',
    label: 'Containers e Kubernetes',
    description: 'Docker, Kubernetes, orquestração de containers e deploy em clusters.',
    bannerColor: 'linear-gradient(135deg, #1e40af, #3b82f6)',
    iconClass: 'box',
    topics: [
      {
        slug: 'docker',
        label: 'Docker',
        description: 'Imagens, containers, Dockerfile, Docker Compose e boas práticas.',
        bannerColor: 'linear-gradient(135deg, #1d4ed8, #2563eb)',
        iconClass: 'box',
        skill: 'Container',
      },
      {
        slug: 'kubernetes',
        label: 'Kubernetes',
        description: 'Pods, Deployments, Services, Ingress, HPA e administração de clusters.',
        bannerColor: 'linear-gradient(135deg, #1e40af, #3b82f6)',
        iconClass: 'box',
        skill: 'Orquestração',
      },
      {
        slug: 'helm',
        label: 'Helm',
        description: 'Charts, releases, repositórios e gerenciamento de aplicações no Kubernetes.',
        bannerColor: 'linear-gradient(135deg, #0e7490, #0891b2)',
        iconClass: 'box',
        skill: 'Kubernetes',
      },
      {
        slug: 'istio',
        label: 'Istio',
        description: 'Service mesh, traffic management, segurança e observabilidade entre serviços.',
        bannerColor: 'linear-gradient(135deg, #4f46e5, #6366f1)',
        iconClass: 'share-2',
        skill: 'Service Mesh',
      },
    ],
  },
  {
    slug: 'devops',
    label: 'DevOps',
    description: 'CI/CD, automação de pipelines, infraestrutura como código e cultura DevOps.',
    bannerColor: 'linear-gradient(135deg, #d97706, #f59e0b)',
    iconClass: 'settings',
    topics: [
      {
        slug: 'ci-cd',
        label: 'CI/CD',
        description: 'Pipelines de integração e entrega contínua, gates de qualidade e automação.',
        bannerColor: 'linear-gradient(135deg, #166534, #16a34a)',
        iconClass: 'rotate-cw',
        skill: 'DevOps',
      },
      {
        slug: 'terraform',
        label: 'Terraform',
        description: 'Infraestrutura como código, providers, state, módulos e boas práticas.',
        bannerColor: 'linear-gradient(135deg, #4f46e5, #7c3aed)',
        iconClass: 'server',
        skill: 'IaC',
      },
      {
        slug: 'github-actions',
        label: 'GitHub Actions',
        description: 'Workflows, jobs, steps, secrets, ambientes e integrações no GitHub.',
        bannerColor: 'linear-gradient(135deg, #374151, #1f2937)',
        iconClass: 'folder-git-2',
        skill: 'CI/CD',
      },
      {
        slug: 'ansible',
        label: 'Ansible',
        description: 'Playbooks, roles, inventários, automação de configuração e provisionamento.',
        bannerColor: 'linear-gradient(135deg, #dc2626, #991b1b)',
        iconClass: 'settings',
        skill: 'Automação',
      },
      {
        slug: 'jenkins',
        label: 'Jenkins',
        description: 'Pipelines declarativos, plugins, agentes e gerenciamento de builds.',
        bannerColor: 'linear-gradient(135deg, #d97706, #f59e0b)',
        iconClass: 'settings',
        skill: 'CI/CD',
      },
    ],
  },
  {
    slug: 'frontend',
    label: 'Frontend',
    description: 'Angular, TypeScript, SCSS, performance web e desenvolvimento de interfaces modernas.',
    bannerColor: 'linear-gradient(135deg, #e59a9a, #d88787)',
    iconClass: 'monitor',
    topics: [
      {
        slug: 'angular',
        label: 'Angular',
        description: 'Componentes standalone, rotas, services, signals e arquitetura moderna com Angular v21.',
        bannerColor: 'linear-gradient(135deg, #c3002f, #dd0031)',
        iconClass: 'monitor',
        skill: 'Framework',
      },
      {
        slug: 'typescript',
        label: 'TypeScript',
        description: 'Tipos, interfaces, generics, decorators e boas práticas para código escalável.',
        bannerColor: 'linear-gradient(135deg, #1565c0, #1976d2)',
        iconClass: 'code',
        skill: 'Linguagem',
      },
      {
        slug: 'scss',
        label: 'SCSS',
        description: 'Variáveis, mixins, nesting, organização de estilos e design tokens.',
        bannerColor: 'linear-gradient(135deg, #bf360c, #e64a19)',
        iconClass: 'palette',
        skill: 'Estilo',
      },
      {
        slug: 'jest',
        label: 'Jest',
        description: 'Testes unitários, mocks, spies e coverage para aplicações frontend.',
        bannerColor: 'linear-gradient(135deg, #1b5e20, #388e3c)',
        iconClass: 'circle-check',
        skill: 'Testes',
      },
      {
        slug: 'primeng',
        label: 'PrimeNG',
        description: 'Componentes visuais modernos, temas, acessibilidade e integração com Angular.',
        bannerColor: 'linear-gradient(135deg, #4a148c, #7b1fa2)',
        iconClass: 'sparkle',
        skill: 'UI',
      },
      {
        slug: 'rxjs',
        label: 'RxJS',
        description: 'Observables, operadores reativos, subjects e controle de streams assíncronos.',
        bannerColor: 'linear-gradient(135deg, #880e4f, #c2185b)',
        iconClass: 'rotate-cw',
        skill: 'Reatividade',
      },
      {
        slug: 'acessibilidade',
        label: 'Acessibilidade',
        description: 'WCAG, ARIA, semântica HTML e navegação inclusiva por teclado.',
        bannerColor: 'linear-gradient(135deg, #00695c, #00897b)',
        iconClass: 'eye',
        skill: 'UX',
      },
      {
        slug: 'responsividade',
        label: 'Responsividade',
        description: 'Mobile first, grid, flexbox, media queries e layouts adaptativos.',
        bannerColor: 'linear-gradient(135deg, #0277bd, #0288d1)',
        iconClass: 'smartphone',
        skill: 'Layout',
      },
      {
        slug: 'design-system',
        label: 'Design System',
        description: 'Tokens de design, componentes reutilizáveis e consistência de UI.',
        bannerColor: 'linear-gradient(135deg, #e59a9a, #d88787)',
        iconClass: 'network',
        skill: 'UI',
      },
      {
        slug: 'html-semantico',
        label: 'HTML Semântico',
        description: 'Estrutura correta de páginas, landmarks, roles ARIA e acessibilidade nativa.',
        bannerColor: 'linear-gradient(135deg, #e65100, #f57c00)',
        iconClass: 'align-left',
        skill: 'Base Web',
      },
      {
        slug: 'performance-web',
        label: 'Performance Web',
        description: 'Core Web Vitals, lazy loading, bundle size e otimização de carregamento.',
        bannerColor: 'linear-gradient(135deg, #b45309, #d97706)',
        iconClass: 'zap',
        skill: 'Performance',
      },
      {
        slug: 'arquitetura',
        label: 'Arquitetura Frontend',
        description: 'Organização de pastas, separação de responsabilidades e padrões de crescimento.',
        bannerColor: 'linear-gradient(135deg, #374151, #4b5563)',
        iconClass: 'building-2',
        skill: 'Arquitetura',
      },
    ],
  },
  {
    slug: 'inteligencia-artificial',
    label: 'Inteligência Artificial',
    description: 'Machine Learning, LLMs, agentes, engenharia de prompts e ferramentas de IA.',
    bannerColor: 'linear-gradient(135deg, #7c3aed, #a855f7)',
    iconClass: 'sparkles',
    topics: [
      {
        slug: 'machine-learning',
        label: 'Machine Learning',
        description: 'Algoritmos supervisionados e não supervisionados, overfitting e avaliação de modelos.',
        bannerColor: 'linear-gradient(135deg, #7c3aed, #a855f7)',
        iconClass: 'sparkles',
        skill: 'ML',
      },
      {
        slug: 'llms',
        label: 'LLMs',
        description: 'Modelos de linguagem de grande escala, fine-tuning, RAG e uso via API.',
        bannerColor: 'linear-gradient(135deg, #4f46e5, #6366f1)',
        iconClass: 'sparkles',
        skill: 'IA',
      },
      {
        slug: 'agentes-ia',
        label: 'Agentes de IA',
        description: 'Agentes autônomos, orquestração, tool use e fluxos multi-agentes.',
        bannerColor: 'linear-gradient(135deg, #0e7490, #0891b2)',
        iconClass: 'bot',
        skill: 'IA',
      },
      {
        slug: 'engenharia-prompts',
        label: 'Engenharia de Prompts',
        description: 'Técnicas de prompting, chain-of-thought, few-shot e estrutura de prompts eficazes.',
        bannerColor: 'linear-gradient(135deg, #d97706, #f59e0b)',
        iconClass: 'pi-pen-to-square',
        skill: 'IA',
      },
      {
        slug: 'mlops',
        label: 'MLOps',
        description: 'Ciclo de vida de modelos, monitoramento, versionamento e deploy em produção.',
        bannerColor: 'linear-gradient(135deg, #166534, #16a34a)',
        iconClass: 'chart-line',
        skill: 'IA',
      },
    ],
  },
  {
    slug: 'observability',
    label: 'Observability',
    description: 'Logs, métricas, tracing distribuído, Grafana, Prometheus e OpenTelemetry.',
    bannerColor: 'linear-gradient(135deg, #059669, #10b981)',
    iconClass: 'eye',
    topics: [
      {
        slug: 'logs',
        label: 'Logs e Logging',
        description: 'Estrutura de logs, agregação, alertas e boas práticas de logging em produção.',
        bannerColor: 'linear-gradient(135deg, #374151, #4b5563)',
        iconClass: 'list',
        skill: 'Observability',
      },
      {
        slug: 'metricas',
        label: 'Métricas',
        description: 'Golden signals, SLIs, SLOs, SLAs e estratégias de medição de sistemas.',
        bannerColor: 'linear-gradient(135deg, #059669, #10b981)',
        iconClass: 'chart-column',
        skill: 'Observability',
      },
      {
        slug: 'tracing',
        label: 'Tracing Distribuído',
        description: 'Rastreamento de requisições, spans, contexto de correlação e visualização.',
        bannerColor: 'linear-gradient(135deg, #0891b2, #0e7490)',
        iconClass: 'eye',
        skill: 'Observability',
      },
      {
        slug: 'grafana',
        label: 'Grafana',
        description: 'Dashboards, datasources, alertas e visualização de séries temporais.',
        bannerColor: 'linear-gradient(135deg, #e65100, #f57c00)',
        iconClass: 'chart-line',
        skill: 'Ferramenta',
      },
      {
        slug: 'prometheus',
        label: 'Prometheus',
        description: 'Coleta de métricas, PromQL, exporters e integração com Grafana.',
        bannerColor: 'linear-gradient(135deg, #dc2626, #ef4444)',
        iconClass: 'database',
        skill: 'Ferramenta',
      },
      {
        slug: 'opentelemetry',
        label: 'OpenTelemetry',
        description: 'Instrumentação, SDK, exporters e padronização de telemetria distribuída.',
        bannerColor: 'linear-gradient(135deg, #4f46e5, #7c3aed)',
        iconClass: 'eye',
        skill: 'Standard',
      },
    ],
  },
  {
    slug: 'performance-engineering',
    label: 'Performance Engineering',
    description: 'Testes de carga, profiling, otimização de sistemas e escalabilidade.',
    bannerColor: 'linear-gradient(135deg, #b45309, #d97706)',
    iconClass: 'chart-line',
    topics: [
      {
        slug: 'testes-carga',
        label: 'Testes de Carga',
        description: 'k6, JMeter, Gatling, análise de resultados e cenários de estresse.',
        bannerColor: 'linear-gradient(135deg, #b45309, #d97706)',
        iconClass: 'chart-line',
        skill: 'Performance',
      },
      {
        slug: 'profiling',
        label: 'Profiling',
        description: 'Análise de CPU, memória, flame graphs e identificação de gargalos.',
        bannerColor: 'linear-gradient(135deg, #0891b2, #0e7490)',
        iconClass: 'search',
        skill: 'Performance',
      },
      {
        slug: 'otimizacao-banco',
        label: 'Otimização de BD',
        description: 'Explain plans, índices, query optimization e tuning de banco de dados.',
        bannerColor: 'linear-gradient(135deg, #166534, #16a34a)',
        iconClass: 'database',
        skill: 'Performance',
      },
      {
        slug: 'cache',
        label: 'Estratégias de Cache',
        description: 'Cache-aside, write-through, TTL, invalidação e padrões de caching.',
        bannerColor: 'linear-gradient(135deg, #4f46e5, #7c3aed)',
        iconClass: 'zap',
        skill: 'Performance',
      },
      {
        slug: 'escalabilidade',
        label: 'Escalabilidade',
        description: 'Scale-out vs scale-up, load balancing, sharding e padrões de crescimento.',
        bannerColor: 'linear-gradient(135deg, #374151, #6b7280)',
        iconClass: 'expand',
        skill: 'Arquitetura',
      },
    ],
  },
  {
    slug: 'projetos',
    label: 'Projetos',
    description: 'Repositório de projetos práticos, experimentos técnicos e portfólio.',
    bannerColor: 'linear-gradient(135deg, #374151, #6b7280)',
    iconClass: 'folder',
    topics: [
      {
        slug: 'personal-platform',
        label: 'Personal Platform',
        description: 'Plataforma pessoal multi-projeto com Angular, automação de deploy e CI/CD.',
        bannerColor: 'linear-gradient(135deg, #4f46e5, #7c3aed)',
        iconClass: 'folder-open',
        skill: 'Projeto',
      },
      {
        slug: 'estudos',
        label: 'Estudos e Labs',
        description: 'Experimentos técnicos, POCs, snippets e repositório de aprendizado.',
        bannerColor: 'linear-gradient(135deg, #0891b2, #0e7490)',
        iconClass: 'book',
        skill: 'Projeto',
      },
    ],
  },
  {
    slug: 'rollout-service',
    label: 'Rollout Service',
    description: 'Feature flags, canary releases, blue/green deployments e deploy gradual.',
    bannerColor: 'linear-gradient(135deg, #047857, #059669)',
    iconClass: 'copy',
    topics: [
      {
        slug: 'feature-flags',
        label: 'Feature Flags',
        description: 'Controle de features em runtime, targeting de usuários e rollout gradual.',
        bannerColor: 'linear-gradient(135deg, #166534, #16a34a)',
        iconClass: 'flag',
        skill: 'Rollout',
      },
      {
        slug: 'canary',
        label: 'Canary Releases',
        description: 'Lançamento gradual para um subconjunto de usuários com monitoramento contínuo.',
        bannerColor: 'linear-gradient(135deg, #d97706, #f59e0b)',
        iconClass: 'copy',
        skill: 'Rollout',
      },
      {
        slug: 'blue-green',
        label: 'Blue/Green Deployments',
        description: 'Ambientes paralelos, switch de tráfego instantâneo e rollback seguro.',
        bannerColor: 'linear-gradient(135deg, #1e40af, #3b82f6)',
        iconClass: 'arrow-left-right',
        skill: 'Deploy',
      },
      {
        slug: 'dark-launch',
        label: 'Dark Launch',
        description: 'Deploy silencioso para validar comportamento antes de expor aos usuários.',
        bannerColor: 'linear-gradient(135deg, #374151, #1f2937)',
        iconClass: 'moon',
        skill: 'Rollout',
      },
    ],
  },
];

export function getSectionBySlug(slug: string): SectionConfig | undefined {
  return STUDY_SECTIONS.find((s) => s.slug === slug);
}

export function getTopicBySlug(sectionSlug: string, topicSlug: string): TopicConfig | undefined {
  return getSectionBySlug(sectionSlug)?.topics.find((t) => t.slug === topicSlug);
}
