import { EnvironmentProviders, Provider } from '@angular/core';
import {
  provideLucideIcons,
  LucideActivity,
  LucideAlignLeft,
  LucideArrowDown,
  LucideArrowLeft,
  LucideArrowLeftRight,
  LucideArrowRight,
  LucideArrowUp,
  LucideBot,
  LucideBox,
  LucideBook,
  LucideBookOpen,
  LucideBriefcase,
  LucideBuilding2,
  LucideCalendar,
  LucideChartColumn,
  LucideChartLine,
  LucideChartPie,
  LucideCheck,
  LucideChevronLeft,
  LucideChevronRight,
  LucideCircle,
  LucideCircleAlert,
  LucideCircleCheck,
  LucideCircleHelp,
  LucideCirclePlay,
  LucideCircleStop,
  LucideClock,
  LucideCloud,
  LucideCode,
  LucideCopy,
  LucideDatabase,
  LucideExpand,
  LucideExternalLink,
  LucideEye,
  LucideEyeOff,
  LucideFile,
  LucideFileText,
  LucideFlag,
  LucideFlame,
  LucideFolder,
  LucideFolderGit2,
  LucideFolderOpen,
  LucideGraduationCap,
  LucideHistory,
  LucideInbox,
  LucideInfo,
  LucideLayoutDashboard,
  LucideLightbulb,
  LucideLink,
  LucideList,
  LucideLoaderCircle,
  LucideLock,
  LucideLogIn,
  LucideLogOut,
  LucideMail,
  LucideMessagesSquare,
  LucideMinus,
  LucideMonitor,
  LucideMoon,
  LucideNetwork,
  LucideNotebookPen,
  LucidePalette,
  LucidePencil,
  LucidePlay,
  LucidePlus,
  LucideRocket,
  LucideRotateCw,
  LucideSearch,
  LucideServer,
  LucideSettings,
  LucideShare2,
  LucideShield,
  LucideSlidersHorizontal,
  LucideSmartphone,
  LucideSparkle,
  LucideSparkles,
  LucideSquarePen,
  LucideStar,
  LucideTag,
  LucideTimer,
  LucideTrash2,
  LucideTrendingUp,
  LucideTriangleAlert,
  LucideUser,
  LucideUsers,
  LucideUtensils,
  LucideVideo,
  LucideWrench,
  LucideBan,
  LucideKey,
  LucidePhone,
  LucideSun,
  LucideUnlock,
  LucideUpload,
  LucideUserCheck,
  LucideUserPlus,
  LucideUserX,
  LucideX,
  LucideZap,
} from '@lucide/angular';

/**
 * Registra todos os ícones Lucide usados pela aplicação.
 * Os nomes ficam disponíveis em lower-kebab-case para o `<app-icon>`
 * (ex: LucideChartPie → "chart-pie").
 */
export function provideAppIcons(): Provider | EnvironmentProviders {
  return provideLucideIcons(
    LucideActivity,
    LucideAlignLeft,
    LucideArrowDown,
    LucideArrowLeft,
    LucideArrowLeftRight,
    LucideArrowRight,
    LucideArrowUp,
    LucideBot,
    LucideBox,
    LucideBook,
    LucideBookOpen,
    LucideBriefcase,
    LucideBuilding2,
    LucideCalendar,
    LucideChartColumn,
    LucideChartLine,
    LucideChartPie,
    LucideCheck,
    LucideChevronLeft,
    LucideChevronRight,
    LucideCircle,
    LucideCircleAlert,
    LucideCircleCheck,
    LucideCircleHelp,
    LucideCirclePlay,
    LucideCircleStop,
    LucideClock,
    LucideCloud,
    LucideCode,
    LucideCopy,
    LucideDatabase,
    LucideExpand,
    LucideExternalLink,
    LucideEye,
    LucideEyeOff,
    LucideFile,
    LucideFileText,
    LucideFlag,
    LucideFlame,
    LucideFolder,
    LucideFolderGit2,
    LucideFolderOpen,
    LucideGraduationCap,
    LucideHistory,
    LucideInbox,
    LucideInfo,
    LucideLayoutDashboard,
    LucideLightbulb,
    LucideLink,
    LucideList,
    LucideLoaderCircle,
    LucideLock,
    LucideLogIn,
    LucideLogOut,
    LucideMail,
    LucideMessagesSquare,
    LucideMinus,
    LucideMonitor,
    LucideMoon,
    LucideNetwork,
    LucideNotebookPen,
    LucidePalette,
    LucidePencil,
    LucidePlay,
    LucidePlus,
    LucideRocket,
    LucideRotateCw,
    LucideSearch,
    LucideServer,
    LucideSettings,
    LucideShare2,
    LucideShield,
    LucideSlidersHorizontal,
    LucideSmartphone,
    LucideSparkle,
    LucideSparkles,
    LucideSquarePen,
    LucideStar,
    LucideTag,
    LucideTimer,
    LucideTrash2,
    LucideTrendingUp,
    LucideTriangleAlert,
    LucideUser,
    LucideUsers,
    LucideUtensils,
    LucideVideo,
    LucideWrench,
    LucideBan,
    LucideKey,
    LucidePhone,
    LucideSun,
    LucideUnlock,
    LucideUpload,
    LucideUserCheck,
    LucideUserPlus,
    LucideUserX,
    LucideX,
    LucideZap,
  );
}

/**
 * Mapa de compatibilidade: nomes legados do PrimeIcons (pi-*) → Lucide.
 * Mantém funcionando os valores de `iconClass` já salvos no banco.
 */
export const PI_TO_LUCIDE: Record<string, string> = {
  'pi-align-left': 'align-left',
  'pi-android': 'bot',
  'pi-arrow-down': 'arrow-down',
  'pi-arrow-left': 'arrow-left',
  'pi-arrow-right': 'arrow-right',
  'pi-arrow-up': 'arrow-up',
  'pi-arrows-h': 'arrow-left-right',
  'pi-bolt': 'zap',
  'pi-book': 'book',
  'pi-box': 'box',
  'pi-briefcase': 'briefcase',
  'pi-building': 'building-2',
  'pi-calendar': 'calendar',
  'pi-chart-bar': 'chart-column',
  'pi-chart-line': 'chart-line',
  'pi-chart-pie': 'chart-pie',
  'pi-check': 'check',
  'pi-check-circle': 'circle-check',
  'pi-chevron-left': 'chevron-left',
  'pi-chevron-right': 'chevron-right',
  'pi-circle': 'circle',
  'pi-clock': 'clock',
  'pi-clone': 'copy',
  'pi-cloud': 'cloud',
  'pi-code': 'code',
  'pi-cog': 'settings',
  'pi-comments': 'messages-square',
  'pi-database': 'database',
  'pi-desktop': 'monitor',
  'pi-exclamation-circle': 'circle-alert',
  'pi-exclamation-triangle': 'triangle-alert',
  'pi-expand': 'expand',
  'pi-external-link': 'external-link',
  'pi-eye': 'eye',
  'pi-file': 'file',
  'pi-file-pdf': 'file-text',
  'pi-fire': 'flame',
  'pi-flag': 'flag',
  'pi-folder': 'folder',
  'pi-folder-open': 'folder-open',
  'pi-github': 'folder-git-2',
  'pi-history': 'history',
  'pi-inbox': 'inbox',
  'pi-info-circle': 'info',
  'pi-lightbulb': 'lightbulb',
  'pi-link': 'link',
  'pi-list': 'list',
  'pi-minus': 'minus',
  'pi-mobile': 'smartphone',
  'pi-moon': 'moon',
  'pi-palette': 'palette',
  'pi-pen-to-square': 'square-pen',
  'pi-pencil': 'pencil',
  'pi-play': 'play',
  'pi-plus': 'plus',
  'pi-prime': 'sparkle',
  'pi-question-circle': 'circle-help',
  'pi-refresh': 'rotate-cw',
  'pi-search': 'search',
  'pi-server': 'server',
  'pi-share-alt': 'share-2',
  'pi-shield': 'shield',
  'pi-sign-out': 'log-out',
  'pi-sitemap': 'network',
  'pi-sliders-h': 'sliders-horizontal',
  'pi-sparkles': 'sparkles',
  'pi-spinner': 'loader-circle',
  'pi-star-fill': 'star',
  'pi-stop-circle': 'circle-stop',
  'pi-stopwatch': 'timer',
  'pi-sync': 'rotate-cw',
  'pi-tag': 'tag',
  'pi-th-large': 'layout-dashboard',
  'pi-times': 'x',
  'pi-trash': 'trash-2',
  'pi-user': 'user',
  'pi-users': 'users',
  'pi-utensils': 'utensils',
  'pi-video': 'video',
  'pi-wrench': 'wrench',
  'pi-youtube': 'circle-play',
};

/**
 * Conjunto de nomes Lucide efetivamente registrados em provideAppIcons().
 * Usado para dar fallback quando um `iconClass` vindo do banco não existe,
 * evitando ícones "invisíveis" (ex.: cards de estudo em /backend).
 */
const REGISTERED_ICONS = new Set<string>([
  'activity', 'align-left', 'arrow-down', 'arrow-left', 'arrow-left-right',
  'arrow-right', 'arrow-up', 'bot', 'box', 'book', 'book-open', 'briefcase',
  'building-2', 'calendar', 'chart-column', 'chart-line', 'chart-pie', 'check',
  'chevron-left', 'chevron-right', 'circle', 'circle-alert', 'circle-check',
  'circle-help', 'circle-play', 'circle-stop', 'clock', 'cloud', 'code', 'copy',
  'database', 'expand', 'external-link', 'eye', 'eye-off', 'file', 'file-text',
  'flag', 'flame', 'folder', 'folder-git-2', 'folder-open', 'graduation-cap',
  'history', 'inbox', 'info', 'layout-dashboard', 'lightbulb', 'link', 'list',
  'loader-circle', 'lock', 'log-in', 'log-out', 'mail', 'messages-square',
  'minus', 'monitor', 'moon', 'network', 'notebook-pen', 'palette', 'pencil',
  'play', 'plus', 'rocket', 'rotate-cw', 'search', 'server', 'settings',
  'share-2', 'shield', 'sliders-horizontal', 'smartphone', 'sparkle', 'sparkles',
  'square-pen', 'star', 'tag', 'timer', 'trash-2', 'trending-up', 'triangle-alert',
  'user', 'users', 'utensils', 'video', 'wrench', 'x', 'zap', 'ban', 'key',
  'phone', 'sun', 'unlock', 'upload', 'user-check', 'user-plus', 'user-x',
]);

/** Ícone padrão quando o nome pedido não está registrado. */
const FALLBACK_ICON = 'book';

/** Converte um nome legado (pi-*) ou já-lucide para o nome registrado. */
export function resolveIconName(name: string | undefined | null): string {
  if (!name) return FALLBACK_ICON;
  const clean = name.replace(/^pi\s+/, '').trim();
  const mapped = PI_TO_LUCIDE[clean] ?? clean;
  return REGISTERED_ICONS.has(mapped) ? mapped : FALLBACK_ICON;
}
